services:
  mysql-db:
    image: mysql:latest
    container_name: db-anonym
    volumes:
      - db-anonym:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: anonym
      MYSQL_DATABASE: anonym
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 3307:3306
    networks:
      - anonym-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql-db
      PMA_USER: root
      PMA_PASSWORD: anonym
    depends_on:
      - mysql-db 
    networks:
      - anonym-network
  backend:
    env_file:
      - ./anonym-back-end/.env
    build:
      context: ./anonym-back-end
      dockerfile: Dockerfile
    container_name: anonym-back-end
    ports:
      - 5000:5000
    depends_on:
      mysql-db:
        condition: service_healthy
    volumes:
      - ./anonym-back-end:/app
      - /app/node_modules
    command: sh -c "npx sequelize-cli db:migrate --config app/config/config.js --migrations-path app/migrations && npm start" 
    develop:
      watch:
        - action: sync
          path: ./anonym-back-end/
          target: /app/
          ignore:
            - node_modules/
        - action: rebuild
          path: ./anonym-back-end/package.json
    networks:
      - anonym-network
  frontend:
    env_file:
    - ./anonym-front-end/.env
    build:
      context: ./anonym-front-end
      dockerfile: Dockerfile
    container_name: anonym-front-end
    ports:
      - 8080:8080
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    volumes:
      - ./anonym-front-end:/app
      - /app/node_modules
    develop:
      watch:
        - action: sync
          path: ./anonym-front-end/
          target: /app/
          ignore:
            - node_modules
        - action: rebuild
          path: ./anonym-front-end/package.json
    networks:
      - anonym-network
    extra_hosts:
      - "ano-nym.local=127.0.0.1"

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - frontend
      - backend
    networks:
      - anonym-network

networks:
  anonym-network:
    driver: bridge

volumes:
  db-anonym: