version: '3.8'

services:
  mysql-db:
    image: mysql:latest
    container_name: db-anonym
    volumes:
      - db-anonym:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 3307:3306
    networks:
      - anonym-network

  backend:
    image: anonym-back-end:latest
    env_file:
      - ./anonym-back-end/.env
    build:
      context: ./anonym-back-end
      dockerfile: Dockerfile
    container_name: anonym-back-end
    ports:
      - 5000:5000
    environment:
      - NODE_ENV=production
    depends_on:
      mysql-db:
        condition: service_healthy
    volumes:
      - ./anonym-back-end:/app
      - /app/node_modules
    command: sh -c "npx sequelize-cli db:migrate --config app/config/config.js --migrations-path app/migrations && npm start"
    networks:
      - anonym-network

  frontend:
    image: anonym-front-end:latest
    env_file:
      - ./anonym-front-end/.env.production
    build:
      context: ./anonym-front-end
      dockerfile: Dockerfile.production
    container_name: anonym-front-end
    ports:
      - 8080:8080
    environment:
        - VITE_NODE_ENV=production
    depends_on:
      - backend
    networks:
      - anonym-network

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/prod.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-enabled-prod:/etc/nginx/sites-enabled-prod
      - ./nginx/nginxconfig.io:/etc/nginx/nginxconfig.io
      - ./nginx/ssl:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - frontend
      - backend
    networks:
      - anonym-network

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./nginx/ssl:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot; sleep 12h; done'"
    networks:
      - anonym-network

networks:
  anonym-network:
    driver: bridge

volumes:
  db-anonym: