FROM node:26.5.1

WORKDIR /app

COPY package*.json ./

RUN npm ci --legacy-peer-deps

COPY . .

RUN npm run build -- --mode preprod
 
EXPOSE 8100

CMD ["npm", "run", "preview", "--", "--mode", "preprod", "--host", "0.0.0.0"]
