FROM node:22.12.0

WORKDIR /app

COPY package*.json ./

RUN npm install --legacy-peer-deps

COPY . .

RUN npm run build -- --mode preprod
 
EXPOSE 8100

CMD ["npm", "run", "preview", "--", "--mode", "preprod"]
