name: Deploy to Production

on:
  pull_request:
    branches:
      - main

jobs:
  prod-deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Production Tests
        run: |
          # Exécutez tous les tests de production pour s'assurer que tout fonctionne avant de déployer
          npm run lint && npm test

      # Deploy to Production
      - name: Deploy to Production
        run: |
          ssh-agent bash -c 'ssh-add <(echo "${{ secrets.PROD_SSH_KEY }}"); ssh -o StrictHostKeyChecking=no ${{ secrets.PROD_USER }}@${{ secrets.PROD_HOST }} << EOF
            git pull origin main
            cd anonym-front-end
            npm run build
            docker-compose -f docker-compose.prod.yml --env-file .env.prod up -d --build
          EOF'