name: ci_worflow

on: 
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - preprod 

jobs:
  security:
    runs-on: ubuntu-latest
 
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # ---- Frontend Snyk Security Check ----
      - name: Run Snyk on Frontend for vulnerabilities
        working-directory: ./anonym-front-end
        run: npx snyk test --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # ---- Backend Snyk Security Check ----
      - name: Run Snyk on Backend for vulnerabilities
        working-directory: ./anonym-back-end
        run: npx snyk test --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_TEST_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.DB_TEST_DATABASE }}
        ports:
          - '3306:3306'
        options: --health-cmd="mysqladmin ping -h localhost --password=password" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.12.0'
    
    # ---- Frontend: Lint, Test, and Build ----
    - name: Install dependencies for Frontend
      working-directory: ./anonym-front-end   # Path to your front-end folder
      run: npm install

    - name: Generate Documentation
      working-directory: ./anonym-front-end
      run: npm run generate-doc

    - name: Run Frontend Lint
      working-directory: ./anonym-front-end   # Lint JavaScript files
      run: npm run lint

    - name: Run Frontend SCSS Lint
      working-directory: ./anonym-front-end   # Lint SCSS files
      run: npm run lint:scss

    - name: Run Frontend Tests
      working-directory: ./anonym-front-end
      run: npm run test -- --ci

    - name: Build Frontend
      working-directory: ./anonym-front-end
      run: npm run build

    # ---- Backend: Lint, Test, Database Setup, and Test Execution ----
    - name: Install dependencies for Backend
      working-directory: ./anonym-back-end
      run: npm install

    - name: Generate Documentation
      working-directory: ./anonym-back-end
      run: npm run generate-doc

    - name: Run Backend Lint 
      working-directory: ./anonym-back-end
      run: npm run lint

    - name: Create Test Database
      working-directory: ./anonym-back-end
      run: npx sequelize-cli db:create --env test --config ./app/config/config.js
      env:
        NODE_ENV: ${{ secrets.NODE_ENV }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
        DB_TEST_USERNAME: ${{ secrets.DB_TEST_USERNAME }}
        DB_TEST_PASSWORD: ${{ secrets.DB_TEST_PASSWORD }}
        DB_TEST_DATABASE: ${{ secrets.DB_TEST_DATABASE }}
        DB_TEST_HOST: ${{ secrets.DB_TEST_HOST }}
        DB_TEST_DIALECT: ${{ secrets.DB_TEST_DIALECT }}
        MAIL_USER: ${{ secrets.MAIL_USER }}
        MAIL_PASS: ${{ secrets.MAIL_PASS }}
        BACK_END_ORIGIN: ${{ secrets.BACK_END_ORIGIN }}
        ORIGIN: ${{ secrets.ORIGIN }}

    - name: Run Migrations on Test Database
      working-directory: ./anonym-back-end 
      run: npx sequelize-cli db:migrate --env test --config ./app/config/config.js --migrations-path ./app/migrations
      env:
        NODE_ENV: ${{ secrets.NODE_ENV }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
        DB_TEST_USERNAME: ${{ secrets.DB_TEST_USERNAME }}
        DB_TEST_PASSWORD: ${{ secrets.DB_TEST_PASSWORD }}
        DB_TEST_DATABASE: ${{ secrets.DB_TEST_DATABASE }}
        DB_TEST_HOST: ${{ secrets.DB_TEST_HOST }}
        DB_TEST_DIALECT: ${{ secrets.DB_TEST_DIALECT }}
        MAIL_USER: ${{ secrets.MAIL_USER }}
        MAIL_PASS: ${{ secrets.MAIL_PASS }}
        BACK_END_ORIGIN: ${{ secrets.BACK_END_ORIGIN }}
        ORIGIN: ${{ secrets.ORIGIN }}

    - name: Run Backend Tests
      working-directory: ./anonym-back-end
      run: npm run test
      env:
        NODE_ENV: ${{ secrets.NODE_ENV }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
        DB_TEST_USERNAME: ${{ secrets.DB_TEST_USERNAME }}
        DB_TEST_PASSWORD: ${{ secrets.DB_TEST_PASSWORD }}
        DB_TEST_DATABASE: ${{ secrets.DB_TEST_DATABASE }}
        DB_TEST_HOST: ${{ secrets.DB_TEST_HOST }}
        DB_TEST_DIALECT: ${{ secrets.DB_TEST_DIALECT }}
        MAIL_USER: ${{ secrets.MAIL_USER }}
        MAIL_PASS: ${{ secrets.MAIL_PASS }}
        BACK_END_ORIGIN: ${{ secrets.BACK_END_ORIGIN }}
        ORIGIN: ${{ secrets.ORIGIN }}